package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Palette (Dynamic Electrical Theme)
val PrimaryLight = Color(0xFF24389C)
val PrimaryContainerLight = Color(0xFF3F51B5)
val OnPrimaryLight = Color(0xFFFFFFFF)
val SecondaryLight = Color(0xFF585D78)
val SecondaryContainerLight = Color(0xFFD9DEFE)
val OnSecondaryLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFFDF8FD)
val SurfaceLight = Color(0xFFFDF8FD)
val SurfaceVariantLight = Color(0xFFE5E1E7)
val SurfaceContainerLowLight = Color(0xFFF7F2F8)
val SurfaceContainerLight = Color(0xFFF1ECF2)
val SurfaceContainerHighLight = Color(0xFFEBE7EC)
val SurfaceContainerHighestLight = Color(0xFFE5E1E7)
val OnSurfaceLight = Color(0xFF1C1B1F)
val OnSurfaceVariantLight = Color(0xFF454652)
val OutlineLight = Color(0xFF757684)
val OutlineVariantLight = Color(0xFFC5C5D4)
val ErrorLight = Color(0xFFBA1A1A)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorLight = Color(0xFFFFFFFF)

// Dark Theme Palette (Premium Tech Dark Theme)
val PrimaryDark = Color(0xFFBAC3FF)
val PrimaryContainerDark = Color(0xFF293CA0)
val OnPrimaryDark = Color(0xFF00105C)
val SecondaryDark = Color(0xFFC0C5E4)
val SecondaryContainerDark = Color(0xFF40465F)
val OnSecondaryDark = Color(0xFF141A31)
val BackgroundDark = Color(0xFF121214)
val SurfaceDark = Color(0xFF1C1B1F)
val SurfaceVariantDark = Color(0xFF454652)
val SurfaceContainerLowDark = Color(0xFF1F1E22)
val SurfaceContainerDark = Color(0xFF252428)
val SurfaceContainerHighDark = Color(0xFF2D2B30)
val SurfaceContainerHighestDark = Color(0xFF37353A)
val OnSurfaceDark = Color(0xFFE5E1E7)
val OnSurfaceVariantDark = Color(0xFFC5C5D4)
val OutlineDark = Color(0xFF8F909F)
val OutlineVariantDark = Color(0xFF454652)
val ErrorDark = Color(0xFFFFB4AB)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorDark = Color(0xFF690005)
