package com.example

import java.util.Locale

object Loc {
    private val strings = mapOf(
        "en" to mapOf(
            "welcome_title" to "Welcome to JK Volt",
            "welcome_subtitle" to "Precision electrical tools engineered for the modern technician.",
            "welcome_vision" to "Operating under the vision of Yumkhaibam Joykumar Singh and proudly developed by the PraXper Android Dev. (PAD) Team.",
            "get_started" to "Get Started",
            "nav_resistor" to "Resistor",
            "nav_ohms_law" to "Ohm's Law",
            "nav_smd_code" to "SMD Code",
            "nav_wire_gauge" to "Wire Gauge",
            "nav_settings" to "Settings",
            "nav_capacitor" to "Capacitor Calculator",
            "nav_terms" to "Terms & Conditions",
            "nav_privacy" to "Privacy Policy",
            "res_band_count" to "%d-Band Resistor",
            "res_band1" to "Band 1 (1st Digit)",
            "res_band2" to "Band 2 (2nd Digit)",
            "res_band3" to "Band 3 (3rd Digit)",
            "res_multiplier" to "Multiplier Band",
            "res_tolerance" to "Tolerance Band",
            "res_temp" to "Temp Coeff Band",
            "res_calc_val" to "CALCULATED RESISTANCE",
            "res_tolerance_val" to "Tolerance: %s",
            "res_calculate" to "Calculate Resistance",
            "ohms_title" to "Enter Any Two Values",
            "ohms_subtitle" to "The other two values will be computed details automatically.",
            "ohms_voltage" to "Voltage (V)",
            "ohms_current" to "Current (I)",
            "ohms_resistance" to "Resistance (R)",
            "ohms_power" to "Power (P)",
            "ohms_volts" to "Volts",
            "ohms_amps" to "Amps",
            "ohms_ohms" to "Ohms",
            "ohms_watts" to "Watts",
            "ohms_clear" to "Clear All",
            "smd_desc" to "Enter SMD Code (3-digit, 4-digit, or EIA-96) to calculate resistance",
            "smd_header" to "RESISTANCE VALUE",
            "smd_ref_title" to "EIA-96 Quick Reference",
            "smd_ref_desc" to "The EIA-96 marking method is a high-precision standard (1%) utilizing two numeric digits for the base table index (01-96) combined with a trailing alphabetic letter to specify its correct multipliers multiplier.",
            "smd_letter_mult" to "Letter -> Multiplier",
            "cap_desc" to "Enter codes found on ceramic, film, or SMD capacitors to instantly convert values between pF, nF, and µF.",
            "cap_header" to "Capacitance Value",
            "cap_ref_title" to "Tolerance Letter Guide",
            "cap_picofarad" to "Picofarads (pF)",
            "cap_nanofarad" to "Nanofarads (nF)",
            "cap_microfarad" to "Microfarads (µF)",
            "cap_placeholder" to "ENTER CAP CODE",
            "cap_identify" to "Identify Components",
            "cap_common" to "COMMON:",
            "wire_gauge_sel" to "Wire Gauge",
            "wire_temp_sel" to "Temp Rating",
            "wire_material_sel" to "Material",
            "wire_phase_sel" to "Phase",
            "wire_copper" to "Copper",
            "wire_aluminum" to "Aluminum",
            "wire_single_phase" to "Single-Phase",
            "wire_three_phase" to "Three-Phase",
            "wire_distance" to "One-Way Distance",
            "wire_sys_volt" to "System Voltage",
            "wire_circuit_load" to "Circuit Current Load",
            "wire_max_safe" to "Max Safe Current",
            "wire_calc_drop" to "Calculated Voltage Drop",
            "wire_suggested_limit" to "Suggested Standard limit: 3.0%",
            "wire_acceptable" to "Acceptable range",
            "wire_exceeds" to "Exceeds suggested limit!",
            "wire_danger" to "DANGER: Current exceeds physical NEC thermal rating limit of %s Amps for %s!",
            "wire_safe_limit" to "Safe thermal rating limit for %s at %s.",
            "wire_rec_title" to "Recommended Wire Size",
            "wire_target_drop" to "Target Drop Limit",
            "wire_dist_unit" to "Distance Unit",
            "ohms_formula_used" to "Formula Used",
            "ohms_step_desc" to "Mathematical steps based on selected parameters",
            "set_personal" to "Personalization",
            "set_legal" to "Legal & Privacy",
            "set_more" to "More",
            "set_theme" to "Theme",
            "set_text" to "Text Size",
            "set_lang" to "Language",
            "set_privacy_sub" to "Zero data collection, 100% offline",
            "set_terms_sub" to "Usage guidelines and safety agreements",
            "set_cap_sub" to "Convert capacitor unit values and codes",
            "set_developed" to "Developed by PAD Team",
            "set_version" to "JK Volt v1.0.0",
            "choose_theme" to "Choose Theme",
            "choose_text" to "Choose Text Size",
            "choose_lang" to "Choose Language",
            "cancel" to "Cancel"
        ),
        "es" to mapOf(
            "welcome_title" to "Bienvenido a JK Volt",
            "welcome_subtitle" to "Herramientas eléctricas de precisión diseñadas para el técnico moderno.",
            "welcome_vision" to "Operando bajo la visión de Yumkhaibam Joykumar Singh y desarrollado con orgullo por el equipo Android Dev de PraXper (PAD).",
            "get_started" to "Empezar",
            "nav_resistor" to "Resistencia",
            "nav_ohms_law" to "Ley de Ohm",
            "nav_smd_code" to "Código SMD",
            "nav_wire_gauge" to "Calibre Cable",
            "nav_settings" to "Ajustes",
            "nav_capacitor" to "Calc. Capacitor",
            "nav_terms" to "Términos y Condiciones",
            "nav_privacy" to "Política de Privacidad",
            "res_band_count" to "Resistencia de %d bandas",
            "res_band1" to "Banda 1 (1er Dígito)",
            "res_band2" to "Banda 2 (2o Dígito)",
            "res_band3" to "Banda 3 (3er Dígito)",
            "res_multiplier" to "Banda de Multiplicador",
            "res_tolerance" to "Banda de Tolerancia",
            "res_temp" to "Banda Coef. de Temp.",
            "res_calc_val" to "RESISTENCIA CALCULADA",
            "res_tolerance_val" to "Tolerancia: %s",
            "res_calculate" to "Calcular Resistencia",
            "ohms_title" to "Ingrese Dos Valores Cualquiera",
            "ohms_subtitle" to "Los otros dos valores se calcularán automáticamente.",
            "ohms_voltage" to "Voltaje (V)",
            "ohms_current" to "Corriente (I)",
            "ohms_resistance" to "Resistencia (R)",
            "ohms_power" to "Potencia (P)",
            "ohms_volts" to "Voltios",
            "ohms_amps" to "Amperios",
            "ohms_ohms" to "Ohmios",
            "ohms_watts" to "Vatios",
            "ohms_clear" to "Limpiar Todo",
            "smd_desc" to "Ingrese el código SMD (3 dígitos, 4 dígitos o EIA-96) para calcular la resistencia",
            "smd_header" to "VALOR DE RESISTENCIA",
            "smd_ref_title" to "Referencia Rápida EIA-96",
            "smd_ref_desc" to "El método de marcado EIA-96 es un estándar de alta precisión (1%) que utiliza dos dígitos numéricos para el índice de la tabla base (01-96) combinados con una letra alfabética final para especificar su multiplicador correcto.",
            "smd_letter_mult" to "Letra -> Multiplicador",
            "cap_desc" to "Ingrese códigos encontrados en capacitores cerámicos, de película o SMD para convertir instantáneamente valores entre pF, nF y µF.",
            "cap_header" to "Valor de Capacitancia",
            "cap_ref_title" to "Guía de Letras de Tolerancia",
            "cap_picofarad" to "Picofaradios (pF)",
            "cap_nanofarad" to "Nanofaradios (nF)",
            "cap_microfarad" to "Microfaradios (µF)",
            "cap_placeholder" to "NÚMERO DE CAP",
            "cap_identify" to "Identificar Componentes",
            "cap_common" to "COMÚN:",
            "wire_gauge_sel" to "Calibre Cable",
            "wire_temp_sel" to "Gama de Temp.",
            "wire_material_sel" to "Material",
            "wire_phase_sel" to "Fase",
            "wire_copper" to "Cobre",
            "wire_aluminum" to "Aluminio",
            "wire_single_phase" to "Monofásico",
            "wire_three_phase" to "Trifásico",
            "wire_distance" to "Distancia Unidireccional",
            "wire_sys_volt" to "Voltaje del Sistema",
            "wire_circuit_load" to "Carga de Corriente del Circuito",
            "wire_max_safe" to "Corriente Máxima Segura",
            "wire_calc_drop" to "Caída de Voltaje Calculada",
            "wire_suggested_limit" to "Límite estándar sugerido: 3.0%",
            "wire_acceptable" to "Rango aceptable",
            "wire_exceeds" to "¡Excede el límite sugerido!",
            "wire_danger" to "PELIGRO: ¡La corriente excede el límite térmico NEC de %s amperios para %s!",
            "wire_safe_limit" to "Límite de clasificación térmica segura para %s a %s.",
            "wire_rec_title" to "Calibre de Cable Recomendado",
            "wire_target_drop" to "Límite de Caída de Voltaje",
            "wire_dist_unit" to "Unidad de Distancia",
            "ohms_formula_used" to "Fórmula Utilizada",
            "ohms_step_desc" to "Pasos matemáticos basados en parámetros seleccionados",
            "set_personal" to "Personalización",
            "set_legal" to "Aspectos Legales",
            "set_more" to "Más",
            "set_theme" to "Tema",
            "set_text" to "Tamaño Texto",
            "set_lang" to "Idioma",
            "set_privacy_sub" to "Sin recopilación de datos, 100% offline",
            "set_terms_sub" to "Pautas de uso y acuerdos de seguridad",
            "set_cap_sub" to "Convertir códigos y valores de capacitores",
            "set_developed" to "Desarrollado por el equipo PAD",
            "set_version" to "JK Volt v1.0.0",
            "choose_theme" to "Elegir Tema",
            "choose_text" to "Elegir Tamaño Texto",
            "choose_lang" to "Elegir Idioma",
            "cancel" to "Cancelar"
        ),
        "hi" to mapOf(
            "welcome_title" to "JK Volt में आपका स्वागत है",
            "welcome_subtitle" to "आधुनिक तकनीशियन के लिए इंजीनियर किए गए सटीक विद्युत उपकरण।",
            "welcome_vision" to "यूमखैबम जोयकुमार सिंह के दृष्टिकोण के तहत संचालित और प्रैक्सपर एंड्रॉइड देव (पीएडी) टीम द्वारा गर्व से विकसित।",
            "get_started" to "शुरू करें",
            "nav_resistor" to "प्रतिरोधक",
            "nav_ohms_law" to "ओह्म का नियम",
            "nav_smd_code" to "SMD कोड",
            "nav_wire_gauge" to "तार का आकार",
            "nav_settings" to "सेटिंग्स",
            "nav_capacitor" to "कैपेसिटर कैलकुलेटर",
            "nav_terms" to "नियम और शर्तें",
            "nav_privacy" to "गोपनीयता नीति",
            "res_band_count" to "%d-बैंड प्रतिरोधक",
            "res_band1" to "बैंड 1 (पहला अंक)",
            "res_band2" to "बैंड 2 (दूसरा अंक)",
            "res_band3" to "बैंड 3 (तीसरा अंक)",
            "res_multiplier" to "गुणक बैंड",
            "res_tolerance" to "सहनशीलता बैंड",
            "res_temp" to "तापमान गुणांक बैंड",
            "res_calc_val" to "परिकलित प्रतिरोध",
            "res_tolerance_val" to "सहनशीलता: %s",
            "res_calculate" to "प्रतिरोध की गणना करें",
            "ohms_title" to "कोई भी दो मान दर्ज करें",
            "ohms_subtitle" to "अन्य दो मानों की गणना स्वचालित रूप से की जाएगी।",
            "ohms_voltage" to "वोल्टेज (V)",
            "ohms_current" to "करंट (I)",
            "ohms_resistance" to "प्रतिरोध (R)",
            "ohms_power" to "शक्ति (P)",
            "ohms_volts" to "वोल्ट",
            "ohms_amps" to "एम्प्स",
            "ohms_ohms" to "ओहज",
            "ohms_watts" to "वाट",
            "ohms_clear" to "सभी साफ करें",
            "smd_desc" to "प्रतिरोध की गणना के लिए SMD कोड (3-अंक, 4-अंक, या EIA-96) दर्ज करें",
            "smd_header" to "प्रतिरोध मान",
            "smd_ref_title" to "EIA-96 त्वरित संदर्भ",
            "smd_ref_desc" to "EIA-96 अंकन विधि एक उच्च-सटीक मानक (1%) है जो आधार तालिका सूचकांक (01-96) के लिए दो संख्यात्मक अंकों का उपयोग करती है और अपने सही गुणक को निर्दिष्ट करने के लिए एक अंतिम वर्णमाला अक्षर लेती है।",
            "smd_letter_mult" to "अक्षर -> गुणक",
            "cap_desc" to "pF, nF, और µF के बीच मानों को तुरंत बदलने के लिए सिरेमिक, फिल्म, या SMD कैपेसिटर पर पाए जाने वाले कोड दर्ज करें।",
            "cap_header" to "कैपेसिटेंस मान",
            "cap_ref_title" to "सहनशीलता पत्र गाइड",
            "cap_picofarad" to "पिकोफैराड (pF)",
            "cap_nanofarad" to "नैनोफैराड (nF)",
            "cap_microfarad" to "माइक्रोफैराड (µF)",
            "cap_placeholder" to "कैप कोड दर्ज करें",
            "cap_identify" to "घटकों की पहचान करें",
            "cap_common" to "सामान्य:",
            "wire_gauge_sel" to "तार का आकार",
            "wire_temp_sel" to "तापमान रेटिंग",
            "wire_material_sel" to "सामग्री",
            "wire_phase_sel" to "चरण",
            "wire_copper" to "तांबा (कॉपर)",
            "wire_aluminum" to "एल्यूमीनियम",
            "wire_single_phase" to "एकल चरण",
            "wire_three_phase" to "त्रि-चरण",
            "wire_distance" to "एक-तरफा दूरी",
            "wire_sys_volt" to "सिस्टम वोल्टेज",
            "wire_circuit_load" to "सर्किट करंट लोड",
            "wire_max_safe" to "अधिकतम सुरक्षित करंट",
            "wire_calc_drop" to "वोल्टेज ड्रॉप की गणना",
            "wire_suggested_limit" to "सुझाया गया मानक सीमा: 3.0%",
            "wire_acceptable" to "स्वीकार्य सीमा",
            "wire_exceeds" to "अनुशंसित सीमा से अधिक है!",
            "wire_danger" to "खतरा: करंट %s के लिए %s एम्प्स की भौतिक NEC तापीय रेटिंग सीमा से अधिक है!",
            "wire_safe_limit" to "%s के लिए %s पर सुरक्षित थर्मल रेटिंग सीमा।",
            "wire_rec_title" to "अनुशंसित तार का आकार (AWG)",
            "wire_target_drop" to "लक्षित वोल्टेज ड्रॉप",
            "wire_dist_unit" to "दूरी इकाई",
            "ohms_formula_used" to "प्रयुक्त सूत्र (Formula)",
            "ohms_step_desc" to "चयनित मापदंडों के आधार पर गणितीय चरण",
            "set_personal" to "निजीकरण",
            "set_legal" to "कानूनी और गोपनीयता",
            "set_more" to "अधिक",
            "set_theme" to "थीम",
            "set_text" to "पाठ का आकार",
            "set_lang" to "भाषा",
            "set_privacy_sub" to "शून्य डेटा संग्रह, 100% ऑफ़लाइन",
            "set_terms_sub" to "उपयोग दिशानिर्देश और सुरक्षा समझौते",
            "set_cap_sub" to "कैपेसिटर यूनिट मान और कोड बदलें",
            "set_developed" to "PAD टीम द्वारा विकसित",
            "set_version" to "JK Volt v1.0.0",
            "choose_theme" to "थीम चुनें",
            "choose_text" to "पाठ का आकार चुनें",
            "choose_lang" to "भाषा चुनें",
            "cancel" to "रद्द करें"
        ),
        "mni" to mapOf(
            "welcome_title" to "JK Volt তা তরাম্না ওকচরি",
            "welcome_subtitle" to "মোদর্ন টেকনিসিয়ানশিংগীদমক পুথোকপা প্রেসিসন ইলেক্ত্রিকেল তুলস।",
            "welcome_vision" to "যুমখাইবাম জোয়কুমার সিংহগী মঙলান মখাদা মথৌ তৌবা অমসুং প্রেক্সপর এন্দ্রোইদ দেব (পেদ) তীমনা চাউথোকচনা পুথোকচবা।",
            "get_started" to "হৌগৎসি",
            "nav_resistor" to "রেসিস্তর",
            "nav_ohms_law" to "ওহমগী লো",
            "nav_smd_code" to "এস.এম.দি. কোদ",
            "nav_wire_gauge" to "ৱায়ার গেজ",
            "nav_settings" to "সেত্তিংস",
            "nav_capacitor" to "কপাসিতর কলকুলেতর",
            "nav_terms" to "নিয়ম অমসুং শর্ত",
            "nav_privacy" to "প্রাইভেসী পোলিসী",
            "res_band_count" to "রেসিস্তর ব্যান্ড %d",
            "res_band1" to "ব্যান্ড ১ (অহানবা দিজিৎ)",
            "res_band2" to "ব্যান্ড ২ (অনীশুবা দিজিৎ)",
            "res_band3" to "ব্যান্ড ৩ (অহুমশুবা দিজিৎ)",
            "res_multiplier" to "মলতিপ্পায়র ব্যান্ড",
            "res_tolerance" to "তোলেরেন্স ব্যান্ড",
            "res_temp" to "তেম্পরেচর কোইফিসিন্ত ব্যান্ড",
            "res_calc_val" to "রেসিস্তেন্স ভেল্যু",
            "res_tolerance_val" to "তোলেরেন্স: %s",
            "res_calculate" to "রেসিস্তেন্স খঙদোকউ",
            "ohms_title" to "ভেল্যু অনী খক ইশিনবীয়ু",
            "ohms_subtitle" to "অন্য ভেল্যু অনীদূ মশানা অপুনবা ওইনা লৌথোক্কনি।",
            "ohms_voltage" to "ভোলতেজ (V)",
            "ohms_current" to "কারেন্ট (I)",
            "ohms_resistance" to "রেসিস্তেন্স (R)",
            "ohms_power" to "পাৱার (P)",
            "ohms_volts" to "ভোল্টস",
            "ohms_amps" to "এম্পস",
            "ohms_ohms" to "ওহমস",
            "ohms_watts" to "ৱাতস",
            "ohms_clear" to "লৌথোকউ",
            "smd_desc" to "রেসিস্তেন্স খঙনবা এস.এম.দি. কোদ ইশিনবীয়ু",
            "smd_header" to "রেসিস্তেন্স ভেল্যু",
            "smd_ref_title" to "EIA-96 কুইক রিফরেন্স",
            "smd_ref_desc" to "EIA-96 মার্কিং তৌবা অসি ১% প্রেসিসন ওইবা মওং অমনি মসিদা দিজিৎ অনী অমসুং মথৌ তৌবা মলতিপ্পায়র লেতর অমা য়াওগনি।",
            "smd_letter_mult" to "লেতর -> মলতিপ্পায়র",
            "cap_desc" to "কপাসিতর কোদ ইশিন্দুনা pF, nF, অমসুং µF ভেল্যুশিং লৌথোকউ।",
            "cap_header" to "কপাসিটেন্স ভেল্যু",
            "cap_ref_title" to "তোলেরেন্স লেতর গাইদ",
            "cap_picofarad" to "পিকোফরাদ (pF)",
            "cap_nanofarad" to "নেনোফরাদ (nF)",
            "cap_microfarad" to "মাইক্রোফরাদ (µF)",
            "cap_placeholder" to "কপাসিতর কোদ ইশিন্নবীয়ু",
            "cap_identify" to "কম্পোনেন্তশিং খঙদোকপা",
            "cap_common" to "কম্মন:",
            "wire_gauge_sel" to "ৱায়ার গেজ",
            "wire_temp_sel" to "তেম্পরেচর রেতিং",
            "wire_material_sel" to "মেতরিএল",
            "wire_phase_sel" to "ফেজ",
            "wire_copper" to "কোপ্পর",
            "wire_aluminum" to "এলুমিনিয়ম",
            "wire_single_phase" to "সিঙ্গল-ফেজ",
            "wire_three_phase" to "থ্রি-ফেজ",
            "wire_distance" to "ৱান-ৱে দিস্তেন্স",
            "wire_sys_volt" to "সিস্তেম ভোলতেজ",
            "wire_circuit_load" to "সার্কিট কারেন্ট লোদ",
            "wire_max_safe" to "মাক্স সেফ কারেন্ট",
            "wire_calc_drop" to "ভোলতেজ দ্রোপ",
            "wire_suggested_limit" to "স্তেন্দর্দ দ্রোপ লিমিৎ: ৩.০%",
            "wire_acceptable" to "সেফ দ্রোপকী মওং",
            "wire_exceeds" to "দ্রোপ হেনখ্রে!",
            "wire_danger" to "অকাইবা: কারেন্ট অসি %s কদমক %s এম্পস কোতকী হেনখ্রে!",
            "wire_safe_limit" to "%s গী তেম্পরেচর %s অমশুং সেফ লিমিৎ অসি ওই।",
            "wire_rec_title" to "রেকমেন্দ পাংলিবা ৱায়ার গেজ",
            "wire_target_drop" to "লক্ষিত দ্রোপ লিমিৎ",
            "wire_dist_unit" to "দিস্তেন্স উনিৎ",
            "ohms_formula_used" to "শীজিন্নরিবা ফর্মুলা",
            "ohms_step_desc" to "আইডেন্তিফাই তৌবা চৎনপথ মথৌ মথৌ",
            "set_personal" to "ব্যক্তিত্ব",
            "set_legal" to "আইন অমসুং প্রাইভেসী",
            "set_more" to "অতোপ্পা",
            "set_theme" to "থিম",
            "set_text" to "ময়েকগী সাইজ",
            "set_lang" to "লোন (ভাষা)",
            "set_privacy_sub" to "দেতা লৌরিবনি অমত্তা লৈতে, ১০০% অফলাইন",
            "set_terms_sub" to "শীজিন্নগী চৎনপথশিং অমসুং সেফতী",
            "set_cap_sub" to "কপাসিতর ভেল্যুশিং অমসুং কোদশিং হোংদোকপা",
            "set_developed" to "PAD তীমনা পুথোকচবা",
            "set_version" to "JK Volt v1.0.0",
            "choose_theme" to "থিম খল্লু",
            "choose_text" to "ময়েকগী সাইজ খল্লু",
            "choose_lang" to "লোন (ভাষা) খল্লু",
            "cancel" to "বাতিল তৌউ"
        )
    )

    fun get(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }

    fun getFormatted(key: String, lang: String, vararg args: Any): String {
        val base = get(key, lang)
        return try {
            String.format(Locale.US, base, *args)
        } catch (e: Exception) {
            base
        }
    }
}
